# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-21 00:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsc_code', models.TextField(blank=True, max_length=500, null=True)),
                ('bsc_token', models.TextField(blank=True, max_length=500, null=True)),
                ('bsc_refresh_token', models.TextField(blank=True, max_length=500, null=True)),
                ('expires_in', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
